// <auto-generated />
namespace NaijaCA_Forum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class titleaddedthread : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(titleaddedthread));
        
        string IMigrationMetadata.Id
        {
            get { return "202306172213372_title-added-thread"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
